Fix NoMethodERror undefined method 'each' for '[path]':String error. paths might be a string instead of an array, because the function that does unix-based enumeration returns a string
git-svn-id: https://www.metasploit.com/svn/framework3/trunk@13970 4d416f70-5f16-0410-b530-b9f4589650da